export const SET_CARD_MODAL_STATE = 'SET_CARD_MODAL_STATE'

export const SET_SELECTED_CARD = 'SET_SELECTED_CARD'

export const ADD_GUESSED_CARD = 'ADD_GUESSED_CARD'

export const RESET_GUESSED_CARDS = 'RESET_GUESSED_CARDS'

export const SET_FEEDBACK = 'SET_FEEDBACK'

export const SET_ALL_CARDS = 'SET_ALL_CARDS'

export const SET_FLASH_CARDS = 'SET_FLASH_CARDS'

export const SET_INTRO_TEXT = 'SET_INTRO_TEXT'

export const SET_DIFFICULTY = 'SET_DIFFICULTY'

export const SELECT_NEW_SET = 'SELECT_NEW_SET'

export const START_NEW_GAME = 'START_NEW_GAME'
