export const SET_CARD_MODAL_STATE = 'SET_CARD_MODAL_STATE'

export const SET_SELECTED_CARD = 'SET_SELECTED_CARD'

export const ADD_GUESSED_CARD = 'ADD_GUESSED_CARD'

export const RESET_GUESSED_CARDS = 'RESET_GUESSED_CARDS'

export const SET_FEEDBACK = 'SET_FEEDBACK'

export const SET_SHARED_CARDS = 'SET_SHARED_CARDS'
